# [公式ドキュメント]
# https://cloud.google.com/appengine/docs/standard/go/config/queueref?hl=ja

# [rate]
# どのくらいの頻度でタスクを実行するか

# [bucket_size]
# 最大同時実行数
# rate/5の値が推奨

# [task_retry_limit]
# 最大試行回数
# 0で処理停止、1でリトライしない、2で1回リトライする

queue:
- name: default
  rate: 100/s
  bucket_size: 25
  retry_parameters:
    task_retry_limit: 1
